
all:
	cd ed2k_client && $(MAKE) all
	cd conn && $(MAKE) all
	cd hash && $(MAKE) all
	cd file && $(MAKE) all

clean:
	cd ed2k_client && $(MAKE) clean
	cd conn && $(MAKE) clean
	cd hash && $(MAKE) clean
	cd file && $(MAKE) clean
