#ifndef __LIBED2K_VERSION__
#define __LIBED2K_VERSION__

#define LIBED2K_VERSION_MAJOR 0
#define LIBED2K_VERSION_MINOR 1
#define LIBED2K_VERSION_TINY  0

#define LIBED2K_VERSION "0.1.0.0"
#define LIBED2K_REVISION "$Rev: 1 $"

#endif
