
all:
	cd https && $(MAKE) all
	cd crypto && $(MAKE) all
	cd ed2k_client && $(MAKE) all
	cd conn && $(MAKE) all
	cd hash && $(MAKE) all
	cd file && $(MAKE) all

clean:
	cd https && $(MAKE) clean
	cd crypto && $(MAKE) clean
	cd ed2k_client $(MAKE) clean
	cd conn && $(MAKE) clean
	cd hash && $(MAKE) clean
	cd file && $(MAKE) clean
