
import os, fnmatch
from os.path import join, basename

def globrec(rootdir, wildcard):
    matches = []
    for root, dirnames, filenames in os.walk(rootdir):
        for filename in fnmatch.filter(filenames, wildcard):
            matches.append(join(root, filename))
    return matches


# Constants 
incdir = 'include'
srcdir = 'src'
bindir = 'bin'

# Environment
boostRoot      = os.getenv('BOOST_ROOT')
libtorrentRoot = os.getenv('LIBTORRENT_ROOT')

# Arguments
args = {
    'CPPPATH' : [incdir] + [join(p, 'include') for p in [boostRoot, libtorrentRoot]],
    'LIBPATH' : [join(p, 'lib') for p in [boostRoot, libtorrentRoot]],
    'LIBS'    : ['boost_system', 'boost_program_options', 'boost_iostreams',
                 'boost_thread', 'boost_signals', 'cryptopp', 'ssl', 'pthread']
    }

env = Environment(**args)
cpps = globrec(srcdir, '*.cpp')
env.Program(join(bindir, 'ed2k_client'), cpps)
